importing

In [14]:
import numpy as np

In [15]:
# set precision
np.set_printoptions(precision= 2)

creating matrix

In [16]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [17]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim) #n dimension

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [18]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3, 2)
3


In [19]:
d = np.array([[[1,2],[2,3],[3,1],[4,5]],[[1,2],[3,1],[3,4],[5,6]]])
print(d)
print(d.shape)
print(d.ndim)

[[[1 2]
  [2 3]
  [3 1]
  [4 5]]

 [[1 2]
  [3 1]
  [3 4]
  [5 6]]]
(2, 4, 2)
3


- generating matrix
  - linear
    -- gap based
    -- element based
  - random
  

In [20]:
np.arange(1,100,5) #1 to 100 at a diff of 5


array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [21]:
a = np.arange(1,10,.2)
print(a)
a.size

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


45

In [22]:
a = np.arange(-np.pi,np.pi,.25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [24]:
b = np.linspace(1,10,100)
print(b)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [25]:
b.reshape(25,4) # 2D

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [26]:
b.reshape(5,5,4) #3D

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [27]:
b.reshape(5,5,2,2) #4D

array([[[[ 1.  ,  1.09],
         [ 1.18,  1.27]],

        [[ 1.36,  1.45],
         [ 1.55,  1.64]],

        [[ 1.73,  1.82],
         [ 1.91,  2.  ]],

        [[ 2.09,  2.18],
         [ 2.27,  2.36]],

        [[ 2.45,  2.55],
         [ 2.64,  2.73]]],


       [[[ 2.82,  2.91],
         [ 3.  ,  3.09]],

        [[ 3.18,  3.27],
         [ 3.36,  3.45]],

        [[ 3.55,  3.64],
         [ 3.73,  3.82]],

        [[ 3.91,  4.  ],
         [ 4.09,  4.18]],

        [[ 4.27,  4.36],
         [ 4.45,  4.55]]],


       [[[ 4.64,  4.73],
         [ 4.82,  4.91]],

        [[ 5.  ,  5.09],
         [ 5.18,  5.27]],

        [[ 5.36,  5.45],
         [ 5.55,  5.64]],

        [[ 5.73,  5.82],
         [ 5.91,  6.  ]],

        [[ 6.09,  6.18],
         [ 6.27,  6.36]]],


       [[[ 6.45,  6.55],
         [ 6.64,  6.73]],

        [[ 6.82,  6.91],
         [ 7.  ,  7.09]],

        [[ 7.18,  7.27],
         [ 7.36,  7.45]],

        [[ 7.55,  7.64],
         [ 7.73,  7.82]],

      

In [28]:
print(np.random.rand(3,3))

[[0.18 0.16 0.55]
 [0.03 0.88 0.61]
 [0.53 0.52 0.8 ]]


In [29]:
print(np.random.randn(5,5)) #random normal

[[ 0.32  0.5   0.34  0.27  0.45]
 [-0.69 -0.57  0.08 -1.7   0.63]
 [-0.77  0.77 -0.83  0.1  -0.24]
 [ 1.64  0.72  2.1  -0.38  0.85]
 [ 0.2   0.5  -0.8   1.33  0.14]]


In [31]:
print(np.random.randint(1,100,(5,3))) #last block for order of matrix

[[74 40 42]
 [99 94 93]
 [96 62 75]
 [92 53 75]
 [88  1 73]]


In [35]:
x = np.random.randint(1,11,(3,3))
y = np.random.randint(1,11,(3,3))
print(x)
print(y)

[[9 4 8]
 [1 8 2]
 [7 9 8]]
[[9 1 8]
 [6 2 9]
 [2 8 5]]


In [36]:
x + y #element wise addition

array([[18,  5, 16],
       [ 7, 10, 11],
       [ 9, 17, 13]])

In [37]:
x - 10

array([[-1, -6, -2],
       [-9, -2, -8],
       [-3, -1, -2]])

In [38]:
x.dot(y) #multiplication of x matrix with y matrix

array([[121,  81, 148],
       [ 61,  33,  90],
       [133,  89, 177]])