In [42]:
import numpy as np

In [43]:
np.set_printoptions(precision= 2)

In [44]:
#1
x = np.zeros(10)
print(x)
print(x.dtype)
print(x.ndim)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
1


In [45]:
#2
y = np.ones(10)
print(y)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [46]:
#3
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
#4
a = np.array([1,2,3,4])
print(a[::-1])

[4 3 2 1]


In [48]:
#5
a = np.array([1,2,3,4,5,6,4,2,3,4,5,6,7])
if (a%2 != 1):
    print(b)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
#6
a = np.array([1,2,3,4])
print(np.mean(a)) #mean
print(np.sum(a)) #sum
print(np.std(a)) #standard deviation

2.5
10
1.118033988749895


In [53]:
#7
n = (np.random.rand(5,5))
print(n)
print(np.max(n))
print(np.min(n))

[[0.29 0.92 0.48 0.81 0.1 ]
 [0.4  0.84 0.07 0.82 0.04]
 [0.83 0.49 0.55 0.2  0.35]
 [0.81 0.11 0.39 0.14 0.29]
 [0.02 0.81 0.8  0.33 0.83]]
0.9226680298775093
0.021325177403859863


In [66]:
#8
n = np.ones((6,6))
print(n)
n[1:-1,1:-1] = 0
print(n)


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [78]:
#9
x = np.random.randint(1,5,(3,3))
print(x)
y = np.random.randint(1,6,(3,3))
print(y)
x.dot(y)



[[2 3 4]
 [2 4 2]
 [2 2 4]]
[[3 2 1]
 [4 5 1]
 [3 1 1]]


array([[30, 23,  9],
       [28, 26,  8],
       [26, 18,  8]])

In [ ]:
#10
