importing

In [2]:
import numpy as np

In [3]:
# set precision
np.set_printoptions(precision= 2)

creating matrix

In [4]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim) #n dimension

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [6]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3, 2)
3


In [7]:
d = np.array([[[1,2],[2,3],[3,1],[4,5]],[[1,2],[3,1],[3,4],[5,6]]])
print(d)
print(d.shape)
print(d.ndim)

[[[1 2]
  [2 3]
  [3 1]
  [4 5]]

 [[1 2]
  [3 1]
  [3 4]
  [5 6]]]
(2, 4, 2)
3


- generating matrix
  - linear
    -- gap based
    -- element based
  - random
  

In [8]:
np.arange(1,100,5) #1 to 100 at a diff of 5


array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [9]:
a = np.arange(1,10,.2)
print(a)
a.size

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


45

In [10]:
a = np.arange(-np.pi,np.pi,.25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [11]:
b = np.linspace(1,10,100)
print(b)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [12]:
b.reshape(25,4) # 2D

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [13]:
b.reshape(5,5,4) #3D

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [14]:
b.reshape(5,5,2,2) #4D

array([[[[ 1.  ,  1.09],
         [ 1.18,  1.27]],

        [[ 1.36,  1.45],
         [ 1.55,  1.64]],

        [[ 1.73,  1.82],
         [ 1.91,  2.  ]],

        [[ 2.09,  2.18],
         [ 2.27,  2.36]],

        [[ 2.45,  2.55],
         [ 2.64,  2.73]]],


       [[[ 2.82,  2.91],
         [ 3.  ,  3.09]],

        [[ 3.18,  3.27],
         [ 3.36,  3.45]],

        [[ 3.55,  3.64],
         [ 3.73,  3.82]],

        [[ 3.91,  4.  ],
         [ 4.09,  4.18]],

        [[ 4.27,  4.36],
         [ 4.45,  4.55]]],


       [[[ 4.64,  4.73],
         [ 4.82,  4.91]],

        [[ 5.  ,  5.09],
         [ 5.18,  5.27]],

        [[ 5.36,  5.45],
         [ 5.55,  5.64]],

        [[ 5.73,  5.82],
         [ 5.91,  6.  ]],

        [[ 6.09,  6.18],
         [ 6.27,  6.36]]],


       [[[ 6.45,  6.55],
         [ 6.64,  6.73]],

        [[ 6.82,  6.91],
         [ 7.  ,  7.09]],

        [[ 7.18,  7.27],
         [ 7.36,  7.45]],

        [[ 7.55,  7.64],
         [ 7.73,  7.82]],

      

In [15]:
print(np.random.rand(3,3))

[[0.36 0.94 0.44]
 [0.73 0.59 0.07]
 [0.99 0.05 0.53]]


In [16]:
print(np.random.randn(5,5)) #random normal

[[-0.98  1.4  -1.44 -0.39  0.2 ]
 [-0.03 -1.52  2.28  0.19  0.68]
 [-0.83 -0.77 -0.02 -0.2  -1.59]
 [ 0.93 -0.85  0.16  0.55 -0.01]
 [-0.93  0.18  0.49  2.19 -0.55]]


In [17]:
print(np.random.randint(1,100,(5,3))) #last block for order of matrix

[[29 28 16]
 [81 88 32]
 [30 74 94]
 [74 81 18]
 [52 61 55]]


In [18]:
x = np.random.randint(1,11,(3,3))
y = np.random.randint(1,11,(3,3))
print(x)
print(y)

[[ 7  8 10]
 [ 1  8  8]
 [ 1  1  4]]
[[10  2  7]
 [ 6  3  2]
 [ 4  8  6]]


In [19]:
x + y #element wise addition

array([[17, 10, 17],
       [ 7, 11, 10],
       [ 5,  9, 10]])

In [20]:
x - 10

array([[-3, -2,  0],
       [-9, -2, -2],
       [-9, -9, -6]])

In [21]:
x.dot(y) #multiplication of x matrix with y matrix

array([[158, 118, 125],
       [ 90,  90,  71],
       [ 32,  37,  33]])

In [22]:
x = np.random.randint(20,50,(6,6))
print(x)

[[37 36 41 26 39 23]
 [42 46 41 35 35 43]
 [31 41 29 37 22 39]
 [29 41 42 36 28 37]
 [24 44 40 40 35 40]
 [33 46 29 46 28 48]]


In [23]:
z = []
for i in x:
    for j in i:
        if j>30:
            z.append(j)
print(np.array(z))
#This is not the best way possible

[37 36 41 39 42 46 41 35 35 43 31 41 37 39 41 42 36 37 44 40 40 35 40 33
 46 46 48]


In [24]:
x > 30 # filter


array([[ True,  True,  True, False,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True],
       [False,  True,  True,  True, False,  True],
       [False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True]])

In [25]:
print(x[x>30]) #boolean filtering

[37 36 41 39 42 46 41 35 35 43 31 41 37 39 41 42 36 37 44 40 40 35 40 33
 46 46 48]


In [26]:
f = x < 40
x[f]

array([37, 36, 26, 39, 23, 35, 35, 31, 29, 37, 22, 39, 29, 36, 28, 37, 24,
       35, 33, 29, 28])

In [27]:
x[(x>30) & (x<45)]

array([37, 36, 41, 39, 42, 41, 35, 35, 43, 31, 41, 37, 39, 41, 42, 36, 37,
       44, 40, 40, 35, 40, 33])

In [28]:
f1 = x > 30
f2 = x < 45
x[f1 & f2]

array([37, 36, 41, 39, 42, 41, 35, 35, 43, 31, 41, 37, 39, 41, 42, 36, 37,
       44, 40, 40, 35, 40, 33])

slicing
- 1D = [start : stop: step]
- 2D = [r_start: r_stop: r_step, c_start: c_stop: c_step]

In [29]:
print('first row')
print(x[0]) #extracts first row from matrix x

first row
[37 36 41 26 39 23]


In [30]:
print('slice 2 to 5')
print(x[2:6])

slice 2 to 5
[[31 41 29 37 22 39]
 [29 41 42 36 28 37]
 [24 44 40 40 35 40]
 [33 46 29 46 28 48]]


In [31]:
x[:,0]

array([37, 42, 31, 29, 24, 33])

In [32]:
x[:, :3] # select first three questions

array([[37, 36, 41],
       [42, 46, 41],
       [31, 41, 29],
       [29, 41, 42],
       [24, 44, 40],
       [33, 46, 29]])

In [33]:
x[:, -1]

array([23, 43, 39, 37, 40, 48])

In [35]:
x[-3 : ] #last three rows

array([[29, 41, 42, 36, 28, 37],
       [24, 44, 40, 40, 35, 40],
       [33, 46, 29, 46, 28, 48]])

In [37]:
x[:, -3:] #last three columns

array([[26, 39, 23],
       [35, 35, 43],
       [37, 22, 39],
       [36, 28, 37],
       [40, 35, 40],
       [46, 28, 48]])